### ISSUE TITLE
Citation information

### ISSUE THREAD

**Issue by yeyuan98** [massimoaria/pubmedR#1]
Hi Prof. Massimo Aria,

I failed to get citation-related metadata using the pipeline described in the vignette. Below is a query I made:

```R
# Define query
query <- "period*[Title/Abstract] AND Drosophila*[Title/Abstract] AND protein*[Title/Abstract] AND english[LA] AND Journal Article[PT]"

# Get a summary of the query
res <- pmQueryTotalCount(query = query, api_key = api_key)

# Download metadata and convert to bibliometrix
D <- pmApiRequest(query = query, limit = res$total_count, api_key = api_key)
M <- pmApi2df(D)
results <- biblioAnalysis(M)
summaryBiblio <- summary(object = results, k = 10)
plot(x = results, k = 10, pause = FALSE)
```

In the `M` data.frame, I found that the column `CR` is filled by NAs and the `TC` column only contains zeros. Otherwise the columns look reasonable.

I wonder what could be the underlying issue. Could you help point out what's going wrong here?

Thanks,
Ye

**Comment by massimoaria** [comment]
This is not an issue.
Pubmed does not provide citations metadata because these are not included in the database!
So some fields will be necessarily empty (i.e. TC, CR, etc.)!
