### ISSUE TITLE
API query results do not match to browser online search

### ISSUE THREAD

**Issue by yeyuan98** [massimoaria/pubmedR#2]
Hi Prof. Massimo Aria,

I ran a query using the pipeline described in the vignette and also tested the same query using Pubmed webpage search. However, the results are not consistent as the total reference counts are not the same:

When I ran the query in R using code shown below, I got 918 hits as shown by `res$total_count`:

```R
# Define query
query <- "period*[Title/Abstract] AND Drosophila*[Title/Abstract] AND protein*[Title/Abstract] AND english[LA] AND Journal Article[PT]"

# Get a summary of the query
res <- pmQueryTotalCount(query = query, api_key = api_key)

# Download metadata and convert to bibliometrix
D <- pmApiRequest(query = query, limit = res$total_count, api_key = api_key)
M <- pmApi2df(D)
results <- biblioAnalysis(M)
summaryBiblio <- summary(object = results, k = 10)
plot(x = results, k = 10, pause = FALSE)
```

However, when I used Pubmed's browser tool (https://pubmed.ncbi.nlm.nih.gov/advanced/#) and pasted the same query `period*[Title/Abstract] AND Drosophila*[Title/Abstract] AND protein*[Title/Abstract] AND english[LA] AND Journal Article[PT]`, I got 1,101 hits.

Could you help identify the problem here?

Thanks a lot for creating the Bibliometrix packages!

Best,
Ye

**Comment by massimoaria** [comment]
If you try to submit your query to the old PubMed website https://www.ncbi.nlm.nih.gov/pubmed,
You obtain the same results as using the API: 918 documents.

The difference appears when using the new site. The query translation system has probably changed in the new interface. In any case, the problem does not depend on pubmedR but on an incorrect alignment between the NCBI API and the new PubMed web interface.
I believe PubMed will solve the issue shortly when the new site replaces the old one as the default system.
