### ISSUE TITLE
pmApiRequest not downloading all records

### ISSUE THREAD

**Issue by zqun1** [massimoaria/pubmedR#8]
Hi, 
   Thanks for developing this package. I really like the output style of _pmApi2df_. However, I found a bug with the _pmApiRequest_ function. Though _pmApiRequest_ states the correct number of records downloaded, data of its return always contain records_downloaded-1 elements. I looked into the source code of _pmApiRequest_ and found that the s=1 (retstart=s in _entrez_fetch_ function) is causing the problem. 
   I manually set s=0 and changed "-s+1" or "+s-1" to s solely. The problem was solved. According to [https://www.ncbi.nlm.nih.gov/books/NBK25499/#_chapter4_EFetch_](url), the default value for retstart is 0. I do not understand why the developer purposely set s (retstart) to 1. 
   Anyway, FYI.

**Comment by massimoaria** [comment]
Hi,
thanks for your remark.
I have solved the issue.
